# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 04:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170411_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='groups',
            field=models.ManyToManyField(blank=True, to='api.Group'),
        ),
    ]
